set(HDRS_Controller
  ${SOURCE_DIR}/Controller/GlobalDefines.h
  ${SOURCE_DIR}/Controller/MainWindow.h
  ${SOURCE_DIR}/Controller/RendererThread.h
  ${SOURCE_DIR}/Controller/ThreadRunner.h
)
set(SRCS_Controller
  ${SOURCE_DIR}/Controller/MainWindow.cpp
  ${SOURCE_DIR}/Controller/RendererThread.cpp
  ${SOURCE_DIR}/Controller/ThreadRunner.cpp
  ${SOURCE_DIR}/Controller/main.cpp
)
