set(MAIN_DIR ${RayTracer_SOURCE_DIR}/..)

set(SOURCE_DIR ${RayTracer_SOURCE_DIR})
set(PROJECT_SOURCE_DIR ${SOURCE_DIR})
set(SOURCE_VIEW_DIR ${SOURCE_DIR}/View)

include_directories (${SOURCE_DIR})

if(UNIX)
set(SYSTEM_FOLDER "linux")
else()
set(SYSTEM_FOLDER "windows")
endif()

set(BIN_DIR ${MAIN_DIR}/bin/${SYSTEM_FOLDER})

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${BIN_DIR}/${CMAKE_BUILD_TYPE})

 #Paths for .a and .so (.dll) libs.
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${MAIN_DIR}/lib/${SYSTEM_FOLDER}/${CMAKE_BUILD_TYPE})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${MAIN_DIR}/lib/${SYSTEM_FOLDER}/${CMAKE_BUILD_TYPE})
