set(HDRS_Model
  ${SOURCE_DIR}/Model/Camera.h
  ${SOURCE_DIR}/Model/Color.h
  ${SOURCE_DIR}/Model/Light.h
  ${SOURCE_DIR}/Model/Material.h
  ${SOURCE_DIR}/Model/ModelDefines.h
  ${SOURCE_DIR}/Model/Object.h
  ${SOURCE_DIR}/Model/Plane.h
  ${SOURCE_DIR}/Model/Point.h
  ${SOURCE_DIR}/Model/Point2D.h
  ${SOURCE_DIR}/Model/Ray.h
  ${SOURCE_DIR}/Model/RenderTileData.h
  ${SOURCE_DIR}/Model/Renderer.h
  ${SOURCE_DIR}/Model/SSEData.h
  ${SOURCE_DIR}/Model/Scene.h
  ${SOURCE_DIR}/Model/SceneFileManager.h
  ${SOURCE_DIR}/Model/Sphere.h
  ${SOURCE_DIR}/Model/Vector.h
  ${SOURCE_DIR}/Model/VisibleObject.h
)
set(SRCS_Model
  ${SOURCE_DIR}/Model/Camera.cpp
  ${SOURCE_DIR}/Model/Object.cpp
  ${SOURCE_DIR}/Model/Plane.cpp
  ${SOURCE_DIR}/Model/Renderer.cpp
  ${SOURCE_DIR}/Model/Scene.cpp
  ${SOURCE_DIR}/Model/SceneFileManager.cpp
  ${SOURCE_DIR}/Model/Sphere.cpp
)
